### ISSUE TITLE
"Grab with rigidbody + mass" and "Grab no action"

### ISSUE THREAD

**Issue by HugoCortell** [ExtendRealityLtd/Tilia.Interactions.Interactables.Unity#38]
## Is your feature request related to a problem?

Not much of an issue just a suggestion.
Its kind of weird that the player can just lift up a 30ton concrete block and a glass bottle all the same.

## Describe the solution you'd like

I would like for two new "grab actions" to be added, the first one being "Grab with rigidbody + mass" which would allow for heavy objects to be grabbed but they would be affected by the rigidbody mass, so a really heavy object might require more force or not move at all if too heavy.  
The second one is "Grab no action", basically, it's grabbing (so it sends the "on grab" and "on ungrab" event) but it does not do anything. This is probably the easiest one to add, but I don't know, I dont understand even a quarter of the VRTK code tbh.

## Describe alternatives you've considered

I tried to disable "set follow to attach point" and a bunch of similar things, but it never gave me the desired result, it was a bit wonky. (Im testing it further right now so ill update if I figure out a better way).

I know theres an option to enable kinematics when grabbed but I saw no difference.

## Additional context

Yeah, I just want the ability to have grabbed objects be affected by their mass.  
Or at least to be able to disable following of grabbed objects.

**Comment by fight4dream** [comment]
for 'Grab no action', my understanding is that you just don't want the object be moved.
I did some testing, just made a cube into interactable,
primary action = follow,
tracking = follow rigidbody,
grab offset = precision point,
secondary action = swap
![image](https://user-images.githubusercontent.com/22952143/88239867-2715a480-ccb8-11ea-9cc4-6204b1b665a4.png)
it is pretty standard.

then, freeze all position and rotation constraints of the rigidbody
![image](https://user-images.githubusercontent.com/22952143/88239985-7360e480-ccb8-11ea-91a0-484f6dade072.png)

the result is:
we can receive the grab/ungrab events, but the cube does not move

**Comment by fight4dream** [comment]
> "Grab with rigidbody + mass" ... so a really heavy object ... not move at all if too heavy.

so the method above would also be the solution for this part of your suggestion
you just need some custom code to determine that if its mass is above a threshold, you'll freeze the rigidbody constraints

**Comment by fight4dream** [comment]
>"Grab with rigidbody + mass" which would allow for heavy objects to be grabbed but they would be affected by the rigidbody mass

again, we use the Follow Rigidbody and Precision Point,
![image](https://user-images.githubusercontent.com/22952143/88241306-53332480-ccbc-11ea-986d-ea974f5976ca.png)
change the Max Distance Delta from default 10 down to 0.1
i can immediately feel it 'difficult to lift'

you can also change its Velocity Limit. test for the combination you feel right for its mass.

**Comment by fight4dream** [comment]
notice the object may no longer move in sync with the hand.
this part has to do with the understanding of what actually happens in real life and what is happening in vr.
let us consider those mass that we feel heavy but still able to lift up in real life, say, a 20lb dumbbell we have to [Front Raise](https://www.youtube.com/watch?v=-t7fuZ0KhDA)
What happen in real life is that, our muscle have trouble lifting it, so we physically only raise it slowly. notice our hand will still be grabbing the dumbbell and the two will move in sync

What happen if we lift the dumbbell in vr?
1. if dumbbell move in sync with our hand, because we can lift our controller as quick as we want (the controller is lightweight), it will give you the 'weird' experience that you don't want
2. the modified rigidbody follow settings represents our muscle strength. It is like a spring is behind the scene. The result is that for objects with mass higher than the spring stiffness can take, the spring would start to sag, and the dumbbell will not move in sync with the hand.

so either you have them move in sync but feels weightless or they not in sync. take your poison.

**Comment by HugoCortell** [comment]
Just tried it and it worked perfectly, thank you my friend!
(PS this might be worth adding to the next braindump, im sure lots of people would love to know too!)
