### ISSUE TITLE
UnityXR - Interactables instruction not working in VR

### ISSUE THREAD

**Issue by hgabor47** [ExtendRealityLtd/Tilia.Interactions.Interactables.Unity#44]
> Your howtoguide works with SpatialSimulator but If I change to UnityXR then not.
I don't find any suggestion/demo for VR.
Please send any link for a VR related doc.

### Steps to reproduce

I followed all steps on your instructions and the SpatialSimulation is working well but if I switched to UnityXR then not. 
https://github.com/ExtendRealityLtd/Tilia.Interactions.Interactables.Unity/tree/master/Documentation/HowToGuides/AddingAnInteractor

### Expected behavior

I can interact with VIVE controllers

### Current behavior

VIVE controllers not interact with the interactable.

**Comment by thestonefox** [comment]
This isn't a bug, this is because you need to configure the button mappings for the unity xr controller.

If you've configured the interactor to work with the simulator then it will only work with the simulator

I suggest you look at the pre-defined mappings in:

https://github.com/ExtendRealityLtd/Tilia.Input.UnityInputManager/tree/master/Runtime/Prefabs/ControllerMappings

**Comment by hgabor47** [comment]
I can't figure out how to use this. :( Sorry but I dig Unity and other tutorials or snippets. Please suggest a learning course if you can.
Thanks Gabor

**Comment by thestonefox** [comment]
try ask either in the slack channel or the discord channel for help. The github issues are for reporting bugs or requesting features.

https://www.vrtk.io/community.html
