### ISSUE TITLE
Interactacle with GrabAction.ControlDirection and PrecisionPoint does not behave correctly

### ISSUE THREAD

**Issue by Xriuk** [ExtendRealityLtd/Tilia.Interactions.Interactables.Unity#73]
### Environment

* Code source: https://github.com/ExtendRealityLtd/Tilia.Interactions.Interactables.Unity
* Code version: 1.15.7
* Platform version: Windows 10 64 bit - Unity 2020.1.7f1
* 3rd party dependencies: none

### Steps to reproduce

- Create a basic VR rig with two interactors
- Drag an Interactable prefab (cube) in the scene
- In the InteractableFacade component set:
   - **Primary Action** to `Interactable.GrabAction.Follow`
   - **Grab Offset** to `Precision Point`
   - **Secondary Action** to `Interactable.GrabAction.ControlDirection`

### Expected behavior

When I grab the cube with the second interactor it should create a new precision point and use it to rotate the cube along with the first precision point.

### Current behavior

When I grab the cube with the second interactor _it seems that it uses the existing precision point_ of the first interactor and it rotates in a weird way.

**Comment by thestonefox** [comment]
This is kinda a short coming of the way the control direction works.

Because you're using a cube it has no distinct forward to know which direction to follow.

So you're getting this output:

![dircubebad1](https://user-images.githubusercontent.com/1029673/108510316-414b4b80-72b6-11eb-84c1-7f4dda6989e8.gif)


So the way the Control Direction is working right now is it follows the distinct forward direction of the mesh (i.e. one part of the mesh has to be protruding forward)

but that forward part needs to be down the z axis otherwise it won't work correctly either.

See here with the long part of the mesh being down the x axis, it doesn't know the correct forward to look at:

![dircubebad2](https://user-images.githubusercontent.com/1029673/108510429-693aaf00-72b6-11eb-90e3-25ae79bf6502.gif)

However, if the long part of the mesh is down the z axis (i.e. the object forward axis) then it works as expected:

![dircubegood](https://user-images.githubusercontent.com/1029673/108510472-79eb2500-72b6-11eb-8b9a-0e7e525f8e01.gif)

---

It would be feasible to be able to provide the axis direction for forward but i'm not sure that would help with a pure square cube.

**Comment by Xriuk** [comment]
So this is indended for guns, stick, or similar? Or can I apply it to a non-square mesh by orientating it towards the forward axis?
As for your last gif, if you'd have grabbed the mesh with the right interactor on the right side first and then the left interactor on the left side (just changing the order of the grab), would it behave the same way or it would have flipped?

**Comment by thestonefox** [comment]
well yeah that's the original intended design to control stick like shapes. But I think your use case (the one in the first gif) "should" work but it is more of a missing feature (which i think can be fixed).

**Comment by Xriuk** [comment]
You could kinda locate the closest axis to the grabbed points and use that, no?

**Comment by thestonefox** [comment]
that would still cause a snap, what it needs is to know the point of collision of the secondary grabbing controller and use that as a value offset from the forward of the grabbed object

**Comment by thestonefox** [comment]
Should be fixed in latest version, the DirectionModifier has some additional options on it now, turning off Snap To LookAt should allow precision grabbing with both controllers.
